website/models.py
from . import db
from flask_login import UserMixin
from sqlalchemy.sql import func

class Memorie(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    data = db.Column(db.String(10000))
    date = db.Column(db.DateTime(timezone=True), default=func.now())
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    likes = db.relationship('Like', backref='post', lazy=True)

class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(150), unique=True)
    password = db.Column(db.String(150))
    user_name = db.Column(db.String(150), unique=True)
    memories = db.relationship('Memorie', backref='user', lazy=True)
    likes = db.relationship('Like', backref='user', lazy=True)



class Like(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    post_id = db.Column(db.Integer, db.ForeignKey('memorie.id'), nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)

website/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from os import path
db = SQLAlchemy()
DB_NAME = "database.db"

from flask_wtf import CSRFProtect

def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'hjshjhdjah kjshkjdhjs'
    app.config['SQLALCHEMY_DATABASE_URI'] = f'sqlite:///{DB_NAME}'
    db.init_app(app)

    csrf = CSRFProtect()
    csrf.init_app(app)

    from .views import views
    from .auth import auth

    app.register_blueprint(views, url_prefix='/')
    app.register_blueprint(auth, url_prefix='/')

    from .models import User, Memorie, Like
    
    with app.app_context():
        db.create_all()

    login_manager = LoginManager()
    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)

    @login_manager.user_loader
    def load_user(id):
        return User.query.get(int(id))

    return app

def create_database(app):
    if not path.exists('website/' + DB_NAME):
        db.create_all(app=app)
        print('Created Database!')

website/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from .models import User
from werkzeug.security import generate_password_hash, check_password_hash
from . import db
from flask_login import login_user, login_required, logout_user, current_user

auth = Blueprint('auth', __name__)

@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')

        user = User.query.filter_by(email=email).first()
        if user and check_password_hash(user.password, password):
            flash('Logged in successfully!', category='success')
            login_user(user, remember=True)
            return redirect(url_for('views.home'))
        else:
            flash('Login failed. Check your email and password.', category='error')

    return render_template('login.html', user=current_user)

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

@auth.route('/sign-up', methods=['GET', 'POST'])
def sign_up():
    if request.method == 'POST':
        email = request.form.get('email')
        user_name = request.form.get('user_name')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')

        if User.query.filter_by(email=email).first():
            flash('Email already exists.', category='error')
        elif password1 != password2:
            flash('Passwords do not match.', category='error')
        else:
            new_user = User(email=email, user_name=user_name, password=generate_password_hash(password1, method='sha256'))
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user, remember=True)
            flash('Account created!', category='success')
            return redirect(url_for('views.home'))

    return render_template('sign-up.html', user=current_user)

website/views.py
from flask import Blueprint, render_template, request, flash, redirect, url_for, jsonify
from flask_login import login_required, current_user
from .models import Memorie, User, Like
from . import db

views = Blueprint('views', __name__)

@views.route('/')
@login_required
def home():
    return render_template('home.html', user=current_user)

@views.route('/main')
@login_required
def main():
    posts = Memorie.query.all()
    liked_posts = [like.post_id for like in current_user.likes]
    return render_template('index.html', user=current_user, posts=posts, liked_posts=liked_posts)

@views.route('/post', methods=['POST'])
@login_required
def add_post():
    content = request.form['content']
    new_post = Memorie(data=content, user_id=current_user.id)
    db.session.add(new_post)
    db.session.commit()
    return redirect(url_for('views.main'))

@views.route('/post/<int:post_id>/like', methods=['POST'])
@login_required
def like_post(post_id):
    post = Memorie.query.get_or_404(post_id)
    like = Like.query.filter_by(user_id=current_user.id, post_id=post.id).first()

    if like:
        db.session.delete(like)
        db.session.commit()
        status = 'unliked'
    else:
        new_like = Like(user_id=current_user.id, post_id=post.id)
        db.session.add(new_like)
        db.session.commit()
        status = 'liked'

    post = Memorie.query.get_or_404(post_id)
    like_count = len(post.likes)

    return jsonify({'status': status, 'like_count': like_count})

website/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <link rel="stylesheet" href="../static/styles.css">
    <script src='https://kit.fontawesome.com/a076d05399.js' crossorigin='anonymous'></script>
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>{% block title %}Home{% endblock %}</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbar">
            <div class="navbar-nav">
                {% if user.is_authenticated %}
                <a class="nav-item nav-link" id="home" href="/">Home</a>
                <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
                {% else %}
                <a class="nav-item nav-link" id="login" href="/login">Login</a>
                <a class="nav-item nav-link" id="signUp" href="/sign-up">Sign Up</a>
                {% endif %}
            </div>
        </div>
    </nav>

    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}
                {% if category == 'error' %}
                <div class="alert alert-danger alert-dismissable fade show" role="alert">
                    {{ message }}
                    <button type="button" class="close" data-dismiss="alert">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                {% else %}
                <div class="alert alert-success alert-dismissable fade show" role="alert">
                    {{ message }}
                    <button type="button" class="close" data-dismiss="alert">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                {% endif %}
            {% endfor %}
        {% endif %}
    {% endwith %}

    <div class="container">{% block content %} {% endblock %}</div>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    {% block javascript %}
    {% endblock %}
</body>
</html>

website/templates/home.html
{% block content %}
<link rel="stylesheet" href="../static/home.css">
<main class='wrapper'>
    <header class='header'>
        <div class='header__logo'>Memoriat</div>
        <div class='header__right'>
            <p>
                <span class='header__language header__active'>EN</span>
                <span class='header__language'>AR</span>
            </p>
            <div class='header__diamond'></div>
        </div>
    </header>
    <nav class='menu'>
        <ul>
            <a href="{{ url_for('views.main') }}">make a memora</a>
            <a href='/logout'>logout</a>
        </ul>
    </nav>
    <div class='bg__pattern'></div>
    <div class='bg__image'></div>
</main>
<script src="../static/home.js"></script>
{% endblock %}

website/templates/index.html
{% extends "base.html" %}

{% block title %}
Home
{% endblock %}

{% block content %}
<div class="container mt-4">
    <h1>Welcome, {{ user.user_name }}</h1>

    <form method="POST" action="{{ url_for('views.add_post') }}">
        <div class="form-group">
            <textarea name="content" class="form-control" rows="3" placeholder="What's on your mind?"></textarea>
        </div>
        <button type="submit" class="btn btn-primary">Post</button>
    </form>

    <hr>

    <div class="posts">
        {% for post in posts %}
        <div class="card my-3">
            <div class="card-body d-flex justify-content-between align-items-center">
                <p>{{ post.data }}</p>
                <footer class="blockquote-footer">
                    Posted by {{ post.user.user_name }} on {{ post.date.strftime('%Y-%m-%d') }}
                </footer>
                <p>Likes: <span class="likes-count">{{ post.likes|length }}</span></p>
                <button class="like-btn" data-post-id="{{ post.id }}">
                    {% if post.id in liked_posts %}Unlike{% else %}Like{% endif %}
                </button>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

<script>
    document.addEventListener('DOMContentLoaded', function () {
        document.querySelectorAll('.like-btn').forEach(button => {
            button.addEventListener('click', function () {
                const postId = this.getAttribute('data-post-id');

                fetch(`/post/${postId}/like`, {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                        'X-CSRFToken': '{{ csrf_token() }}'
                    }
                })
                    .then(response => response.json())
                    .then(data => {
                        if (data.status === 'liked') {
                            this.textContent = 'Unlike';
                        } else {
                            this.textContent = 'Like';
                        }
                        this.closest('.card-body').querySelector('.likes-count').textContent = data.like_count;
                    });
            });
        });
    });
</script>
{% endblock %}

website/templates/login.html
{% block title %}Login{% endblock %} {% block content
%}
<link rel="stylesheet" href="../static/login.css">
<form method="POST">
  <div class="ring">
    <i style="--clr:#82a8b3;"></i>
    <i style="--clr:#f6eadc;"></i>
    <i style="--clr:#0d1345;"></i>
    <div class="login">
      <h2>Login</h2>
      <div class="form-group">
        <input type="email" class="form-control" id="email" name="email" placeholder="Enter email" />
      </div>
      <div class="form-group">
        <input type="password" class="form-control" id="password" name="password" placeholder="Enter password" />
      </div>
      <div class="form-group">
        <button type="submit" class="btn btn-primary">Login</button>
      </div>
      <div class="links">
        <a href="sign-up">Signup</a>
      </div>
    </div>
  </div>
</form>
{% endblock %}
<!--ring div starts here-->

website/templates/sign-up.html
{% block title %}Sign Up{% endblock %} {% block
content %}
<link rel="stylesheet" href="../static/sign-up.css">
<form method="POST">
    <div class="ring">
        <i style="--clr:#82a8b3;"></i>
        <i style="--clr:#f6eadc;"></i>
        <i style="--clr:#0d1345;"></i>
        <div class="login">
            <h2>Sign up</h2>
            <div class="form-group">

                <input type="email" class="form-control" id="email" name="email" placeholder="Enter email" />
            </div>
            <div class="form-group">
                <input type="text" class="form-control" id="user_name" name="user_name"
                    placeholder="Enter user name" />
            </div>
            <div class="form-group">
                <input type="password" class="form-control" id="password1" name="password1"
                    placeholder="Enter password" />
            </div>
            <div class="form-group">
                <input type="password" class="form-control" id="password2" name="password2"
                    placeholder="Confirm password" />
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
            <div class="links">
                <a href="/login">Login</a>
            </div>
        </div>
    </div>
</form>
{% endblock %}